sonar.projectKey=STQAProject
sonar.projectName=STQAProject

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token= sqp_96358fddbbc8db6b51c113123689b7919f0a3ba7



